namespace Flare.Syntax
{
    public enum SyntaxDiagnosticKind
    {
        UnrecognizedCharacter,
        IncompleteFragmentIdentifier,
        IncompleteIntegerLiteral,
        IncompleteRealLiteral,
        IncompleteStringLiteral,
        IncompleteEscapeSequence,
        MissingToken,
        SkippedToken,
        MissingNamedDeclaration,
        MissingExpression,
        MissingPattern,
        DuplicateUseDeclarationAlias,
        InvalidDeclarationName,
        DuplicateDeclaration,
        DuplicateParameter,
        InvalidAssignmentTarget,
        UnknownValueName,
        DiscardedVariableUsed,
        DuplicateExpressionField,
        InvalidLoopTarget,
        DuplicatePatternField,
        ModuleLoadFailed,
        InvalidLintAttribute,
        Lint,
    }
}
