# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Release
on:
    release:
        types:
            - published
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
jobs:
    release:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.6.0
              with:
                  dotnet-version: 5.0.100-preview.8.20417.9
            - name: Install dependencies
              run: |
                  dotnet tool restore
                  dotnet restore
            - name: Pack project
              run: |
                  dotnet pack -c Release --no-build
            - name: Publish project
              run: |
                  rids="linux-arm linux-arm64 linux-x64 osx-x64 win-arm win-arm64 win-x64 win-x86"
                  for rid in $rids; do
                      dotnet publish -c Release -r $rid -p:PublishSingleFile=true
                  done
            - name: Upload NuGet packages
              if: github.repository == 'flare-lang/flare'
              run: |
                  dotnet nuget push src/*/bin/Release/*.{nupkg,snupkg} -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
            - name: Upload GitHub packages
              uses: svenstaro/upload-release-action@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref }}
                  file: src/cli/bin/Release/*.zip
                  file_glob: true
